_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.10.13
            "5": 0.18.7
            "6": 4.46.2
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batch_size_training:
    value: 8
bf16:
    value: false
c_thought:
    value: 1
coconut:
    value: true
cot:
    value: false
debug:
    value: false
epochs_per_stage:
    value: 5
gradient_accumulation_steps:
    value: 1
load_model_path:
    value: checkpoints/prosqa-coconut/checkpoint_5
lr:
    value: 0.0001
max_latent_stage:
    value: 6
model_id:
    value: openai-community/gpt2
name:
    value: prosqa-coconut
no_cot:
    value: false
no_thoughts:
    value: false
num_epochs:
    value: 50
only_eval:
    value: false
pad_latent_to_max:
    value: true
project:
    value: coconut
reset_optimizer:
    value: true
resume:
    value: 5
save_only_improve:
    value: false
save_path:
    value: checkpoints
seed:
    value: 0
train_path:
    value: data/prosqa_train.json
uniform_prob:
    value: 0
val_path:
    value: data/prosqa_valid.json
weight_decay:
    value: 0.01
