# need 4 gpus

project: coconut
save_path: checkpoints
name: prosqa-coconut

only_eval: False

coconut: True
cot: False
no_thoughts: False
no_cot: False

c_thought: 1
epochs_per_stage: 5
max_latent_stage: 6
pad_latent_to_max: True

save_only_improve: False
uniform_prob: 0.0

# Removal smoothing parameters for stabilizing training
removal_smoothing_lambda: 4.0    # Î» parameter controlling smoothing strength (higher = less smoothing)
removal_smoothing_max_offset: 2  # Maximum offset to apply (typically 1-2)
model_id: openai-community/gpt2
load_model_path: None
seed: 0
resume: 0
bf16: False
train_path: data/prosqa_train.json
val_path: data/prosqa_valid.json
reset_optimizer: True
batch_size_training: 8
debug: False
gradient_accumulation_steps: 1
num_epochs: 50
lr: !!float "1e-4"
weight_decay: 0.01